Select * from customer;


--Q1. What is the total revenue generated by male vs. female customers?

select  gender, round(sum(purchase_amount) as revenvue from [dbo].[customer]
group by gender 

--Q2. Which customers used a discount but still spent more than the average purchase amount? 

select customer_id, purchase_amount
from [dbo].[customer]
where discount_applied = 'Yes' and purchase_amount >=(
select avg (purchase_amount)
from [dbo].[customer])


-- Q3. Which are the top 5 products with the highest average review rating?
select top 5 item_purchased, round(AVG(review_rating),2) as avg_rating
from [dbo].[customer]
group by item_purchased
order by avg(review_rating) desc


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

select shipping_type , round(AVG(purchase_amount),2) as avg_amount
from [dbo].[customer]
group by shipping_type

order by 2 desc


--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select subscription_status,Count(*) As total_customer , round(AVG(purchase_amount),2) as avg_amount, round(sum(purchase_amount),2) as total_amount
from [dbo].[customer]
group by subscription_status

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT top 5 item_purchased,
       ROUND(100.0 * SUM(
	   CASE 
				WHEN discount_applied = 'Yes' THEN 1 
	   ELSE 0 
	   END)/COUNT(*),3) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.

with CTE as(
select 
case
when previous_purchases <= 1 then 'new'
when previous_purchases >= 2 and previous_purchases <= 10 then 'returning'
else 'loyal'
end As Customer_segment
from [dbo].[customer]
)

select Customer_segment,count(*) as "Number of Customers"
from CTE group by Customer_segment;





--Q8. What are the top 3 most purchased products within each category? 

with Cte as (
select count(item_purchased) as total,category,item_purchased,
	ROW_NUMBER() over (partition by category order by count(customer_id)desc)  as Rank1
from [dbo].[customer]
group by category,item_purchased

)

select category,item_purchased from Cte
where Rank1 <=3


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select count(*) as Repeat_customers, subscription_status
from [dbo].[customer]
where previous_purchases >5
group by subscription_status

--Q10. What is the revenue contribution of each age group? 

	select sum(purchase_amount) as revenue,age_group,gender
	from [dbo].[customer]
	group by age_group,gender
	order by 1 desc

